# Generated by Django 6.0.4 on 2026-04-18 03:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("products", "0001_initial"),
        ("suppliers", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="productinfo",
            name="supplier",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="products",
                to="suppliers.supplier",
            ),
        ),
        migrations.AddField(
            model_name="productparameter",
            name="parameter",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="products.parameter"
            ),
        ),
        migrations.AddField(
            model_name="productparameter",
            name="product_info",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="parameters",
                to="products.productinfo",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="productinfo",
            unique_together={("product", "supplier")},
        ),
    ]
